#!/bin/sh

ssh -t -t ec2-user@172.31.56.69 <<EOF 

  cd ~/deployable-todo-node

  git pull origin for-jenkins

  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.3/install.sh | bash

  . ~/.nvm/nvm.sh

  export NVM_DIR="~/.nvm"
#   export NVM_DIR="$HOME/.nvm"  

  nvm install 16.19.0

  nvm use 16.19.0

  npm install

  npm install -g pm2

  pm2 kill

  npm run start-prod
  
#   sudo yum install nginx -y

  sudo amazon-linux-extras install nginx1 -y

  sudo mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old

  sudo cp ./script/nginx.conf /etc/nginx/

  sudo nginx -t

  sudo chkconfig nginx on

  sudo systemctl restart nginx

  exit

EOF